TPP_MainProject/Controllers/AdminUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Owin;
using TPP_MainProject.Models;
using TPP_MainProject.Models.entities;
using TPP_MainProject.Models.repository;
using TPP_MainProject.Models.ViewModels;
using System.Collections.ObjectModel;
using TPP_MainProject.Models.constants;
using System.Data.Entity;
using PagedList;

namespace TPP_MainProject.Controllers
{
    public class AdminUserController : Controller
    {        
        private ApplicationUserManager _userManager;
        private UnitOfWork unityOfWork = new UnitOfWork();
       // ApplicationUser user;

        public AdminUserController()
        { }
        public AdminUserController(ApplicationUserManager userManager)
        {
            UserManager = userManager;
        }

        public ApplicationUserManager UserManager {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

     
        // GET: AdminUser

        private ApplicationDbContext _db = new ApplicationDbContext();

       
        //
        // GET: /Admin/Index
        [AllowAnonymous]
        [Authorize(Roles = "Admin")]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString,int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";
            ViewBag.RoleSortParm = sortOrder == "Role" ? "Role_desc" : "Role";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var rolesList = new Collection<AdminUserViewModel>();
            var users = from s in _db.Users
                        select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(s => s.UserName.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "Name_desc":
                    users = users.OrderByDescending(s => s.UserName);
                    break;
                case "Role":
                    users = users.OrderBy(s => s.RoleName);
                    break;
                case "Role_desc":
                    users = users.OrderByDescending(s => s.RoleName);
                    break;
                default:
                    users = users.OrderBy(s => s.UserName);
                    break;
            }
            foreach (var role in users)
            {
                var moselItem = new AdminUserViewModel(role);
                rolesList.Add(moselItem);
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(rolesList.ToPagedList(pageNumber, pageSize));
            
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.roles = _db.Roles.ToList();
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
         public ActionResult Create(AdminUserViewModel model)
        {

            if (ModelState.IsValid)
            {
                var role = model.RoleName;

                /*  
                  switch (role)
                  { 
                          /*NEED TO CHANGE - gamnocode*/
                /*
                    case RolesConst.ADMIN:
                        this.user = new ApplicationUser()
                        {
                            UserName = model.Email,
                            Email = model.Email,
                            FistName = model.FistName,
                            LastName = model.LastName,
                            Organization = model.Organization,
                            City = model.City,
                            Country = model.Country,
                            RoleName = model.RoleName
                        };
                        break;
                    case RolesConst.ACCOUNTANT:
                        this.user = new Accountant()
                        {
                            UserName = model.Email,
                            Email = model.Email,
                            FistName = model.FistName,
                            LastName = model.LastName,
                            Organization = model.Organization,
                            City = model.City,
                            Country = model.Country,
                            RoleName = model.RoleName
                        };
                        break;
                    case RolesConst.RESOURSE_MANAGER:
                        this.user = new ResourceManager()
                        {
                            UserName = model.Email,
                            Email = model.Email,
                            FistName = model.FistName,
                            LastName = model.LastName,
                            Organization = model.Organization,
                            City = model.City,
                            Country = model.Country,
                            RoleName = model.RoleName
                        };
                        break;
                    case RolesConst.CUSTOMER:
                        this.user = new Customer()
                        {
                            UserName = model.Email,
                            Email = model.Email,
                            FistName = model.FistName,
                            LastName = model.LastName,
                            Organization = model.Organization,
                            City = model.City,
                            Country = model.Country,
                            RoleName = model.RoleName
                        };

                        break;
                    case RolesConst.HR:
                        this.user = new HR()
                        {
                            UserName = model.Email,
                            Email = model.Email,
                            FistName = model.FistName,
                            LastName = model.LastName,
                            Organization = model.Organization,
                            City = model.City,
                            Country = model.Country,
                            RoleName = model.RoleName
                        };
                        break;
                    case RolesConst.MANAGER:
                        this.user = new Manager()
                        {
                            UserName = model.Email,
                            Email = model.Email,
                            FistName = model.FistName,
                            LastName = model.LastName,
                            Organization = model.Organization,
                            City = model.City,
                            Country = model.Country,
                            RoleName = model.RoleName
                        };
                        break;
                    case RolesConst.OPERATOR:
                        this.user = new Operator()
                        {
                            UserName = model.Email,
                            Email = model.Email,
                            FistName = model.FistName,
                            LastName = model.LastName,
                            Organization = model.Organization,
                            City = model.City,
                            Country = model.Country,
                            RoleName = model.RoleName
                        };
                        break;
                    case RolesConst.PROGRAMER:
                        this.user = new Programmer()
                        {
                            UserName = model.Email,
                            Email = model.Email,
                            FistName = model.FistName,
                            LastName = model.LastName,
                            Organization = model.Organization,
                            City = model.City,
                            Country =
                            model.Country,
                            RoleName = model.RoleName
                        };
                        break;
                    default:
                        this.user = new Customer()
                        {
                            UserName = model.Email,
                            Email = model.Email,
                            FistName = model.FistName,
                            LastName = model.LastName,
                            Organization = model.Organization,
                            City = model.City,
                            Country = model.Country,
                            RoleName = model.RoleName
                        };
                        break;

                }
               */
                var user = new Customer()
                {
                    UserName = model.Email,
                    Email = model.Email,
                    FistName = model.FistName,
                    LastName = model.LastName,
                    Organization = model.Organization,
                    City = model.City,
                    Country = model.Country,
                    RoleName = model.RoleName
                };
              

TPP_MainProject/Controllers/DistributorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TPP_MainProject.Models;
using TPP_MainProject.Models.constants;
using TPP_MainProject.Models.ViewModels;

namespace TPP_MainProject.Controllers
{
    public class DistributorController : Controller
    {

        private ApplicationDbContext _db = new ApplicationDbContext();


        // GET: /Distributor/
        public ActionResult Index()
        {
            //var rolesList = new List<RoleViewModel>();
            //foreach (var role in _db.Roles)
            //{
            //    var roleModel = new RoleViewModel(role);
            //    rolesList.Add(roleModel);
            //}
            if (User.IsInRole(RolesConst.ACCOUNTANT))
            {
                return RedirectToAction("Index", RolesConst.ACCOUNTANT);
            }
            if (User.IsInRole(RolesConst.PROGRAMER))
            {
                return RedirectToAction("Index", RolesConst.PROGRAMER);
            }
            if (User.IsInRole(RolesConst.OPERATOR))
            {
                return RedirectToAction("Index", RolesConst.OPERATOR);
            }
            if (User.IsInRole(RolesConst.RESOURSE_MANAGER))
            {
                return RedirectToAction("Index", RolesConst.RESOURSE_MANAGER+"s");
            }
            if (User.IsInRole(RolesConst.Sales_MANAGER))
            {
                return RedirectToAction("Index", "Items");
            }
            if (User.IsInRole(RolesConst.ORDER_OPERATOR))
            {
                return RedirectToAction("Index", RolesConst.ORDER_OPERATOR);
            }
            if(User.IsInRole(RolesConst.CUSTOMER))
            {
                return RedirectToAction("Index", RolesConst.CUSTOMER);
            }
            if (User.IsInRole(RolesConst.MANAGER))
            {
                return RedirectToAction("Index", RolesConst.MANAGER);
            }
            //_db.Dispose();
             return RedirectToAction("About", "Home");;
        }

       
	}
}

TPP_MainProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
  ]
</head>
<body style='background: #D0F5A9'>
    <p>
        <div class="navbar navbar-inverse navbar-fixed-top" style="background:#214552; color:#fff;">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    @Html.ActionLink("Choose&Enjoy", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @if (Request.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("My cabinet", "Index", "Distributor")</li>


                            if (User.IsInRole("Admin"))
                            {
                                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                <li>@Html.ActionLink("Roles", "Index", "Roles")</li>
                                <li>@Html.ActionLink("Users", "Index", "AdminUser")</li>
                            }

                        }
                        @* For unknown user *@
                        else
                        {

                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>


                        }

                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer style="color:#0B610B; font-family:'Segoe Print'; font-weight:bold">
    <p>&copy; @DateTime.Now.Year - Company "Choose&Enjoy"</p>
    </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")"
            type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")"
            type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")"
            type="text/javascript"></script>

</body>
</html>