TPP_MainProject/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TPP_MainProject.Models;
using TPP_MainProject.Models.constants;
using TPP_MainProject.Models.entities;
using TPP_MainProject.Models.repository;

namespace TPP_MainProject.Controllers
{
    public class CheckoutController : Controller
    {
        UnitOfWork unitOfWork = new UnitOfWork();
        // GET: Checkout
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "Customer")]
        public ActionResult AddressAndPayment()
        {
            return View();
        }
        // POST: /Checkout/AddressAndPayment
        [HttpPost]
        [Authorize(Roles = "Customer")]
        public ActionResult AddressAndPayment(FormCollection values)
        {
            var order = new Order();
            TryUpdateModel(order);

            //try
            //{
               /* if (string.Equals(values["PromoCode"], PromoCode,
                    StringComparison.OrdinalIgnoreCase) == false)
                {
                    return View(order);
                }
                else
                {*/
                   // order.customer.UserName = User.Identity.Name;
                    order.OrderDate = DateTime.Now;
                    order.completeDate = DateTime.Now;
                    order.orderStartus = OrderStatus.Initiating;
                    order.detailDescription = values[0];
                   
                    order.customer =(Customer) unitOfWork.CustomerRepository.dbSet.Where(s => s.UserName.Equals(User.Identity.Name)).First();
                  

                    //Save Order
                    unitOfWork.OrderRepository.Insert(order);
                    unitOfWork.Save();
                    //Process the order
                    var cart = OrderCart.GetCart(this);
                 //   order.orderItems = new Collection<ProductItem>();
                    cart.CreateOrder(order);
                    unitOfWork.Save();

                    return RedirectToAction("Complete",
                        new { id = order.OrderId });
                   
                //}
           // }
            //catch
            //{
                //Invalid - redisplay with errors
            //    return View(order);
           // }
        }
        // GET: /Checkout/Complete
        public ActionResult Complete(int id)
        {
            // Validate customer owns this order
            bool isValid = unitOfWork.OrderRepository.dbSet.Any(
                o => o.OrderId == id &&
                o.customer.UserName == User.Identity.Name);

            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }
    }
}

TPP_MainProject/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using TPP_MainProject.Models;
using TPP_MainProject.Models.repository;
using TPP_MainProject.Models.entities;
using TPP_MainProject.Models.constants;

namespace TPP_MainProject.Controllers
{
    public class ItemsController : Controller
    {
        private UnitOfWork unityOfWork = new UnitOfWork();
        //private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Items
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "price_desc" : "Price";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var items = from i in unityOfWork.ProductItemRepository.dbSet
                           select i;
            if (!String.IsNullOrEmpty(searchString))
            {
                items = items.Where(s => s.Name.ToUpper().Contains(searchString.ToUpper())
                                       || s.Categorie.ToString().ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    items = items.OrderByDescending(s => s.Name);
                    break;
                case "Price":
                    items = items.OrderBy(s => s.Price);
                    break;
                case "price_desc":
                    items = items.OrderByDescending(s => s.Price);
                    break;
                default:  // Name ascending 
                    items = items.OrderBy(s => s.Name);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View( items.ToPagedList(pageNumber, pageSize));


            //var items = db.Items.Include(i => i.Catagorie);
            //return View(await items.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductItem item = await unityOfWork.ProductItemRepository.dbSet.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

       
        // GET: Items/Create
        [Authorize(Roles = "SalesManager")]
        public ActionResult Create()
        {
           // ViewBag.CatagorieId = new SelectList(TemplateSiteTypes);
            return View();
        }

        // POST: Items/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SalesManager")]
        public async Task<ActionResult> Create(ProductItem item)
        {
            if (ModelState.IsValid)
            {
                unityOfWork.ProductItemRepository.context.ProductItems.Add(item);
               // db.Items.Add(item);
                await unityOfWork.ProductItemRepository.context.SaveChangesAsync();
                //await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

           // ViewBag.CatagorieId = new SelectList(db.Catagories, "ID", "Name", item.CatagorieId);
            return View(item);
        }

        // GET: Items/Edit/5
         [Authorize(Roles = "SalesManager")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductItem item = await unityOfWork.ProductItemRepository.context.ProductItems.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
           // ViewBag.CatagorieId = new SelectList(db.Catagories, "ID", "Name", item.CatagorieId);
            return View(item);
        }

        // POST: Items/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SalesManager")]
        public async Task<ActionResult> Edit(ProductItem item)
        {
            if (ModelState.IsValid)
            {
                unityOfWork.ProductItemRepository.context.Entry(item).State = EntityState.Modified;
                await unityOfWork.ProductItemRepository.context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            //ViewBag.CatagorieId = new SelectList(db.Catagories, "ID", "Name", item.CatagorieId);
            return View(item);
        }

        // GET: Items/Delete/5
         [Authorize(Roles = "SalesManager")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ProductItem item = await unityOfWork.ProductItemRepository.context.ProductItems.FindAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SalesManager")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ProductItem item = await unityOfWork.ProductItemRepository.context.ProductItems.FindAsync(id);
            unityOfWork.ProductItemRepository.context.ProductItems.Remove(item);
            await unityOfWork.ProductItemRepository.context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> RenderImage(int id)
        {
            ProductItem item = await unityOfWork.ProductItemRepository.context.ProductItems.FindAsync(id);

            byte[] photoBack = item.InternalImage;

            return File(photoBack, "image/png");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unityOfWork.ProductItemRepository.context.Dispose();
            }
            base.Dispose(disposing);
        }
       
    }
}

TPP_MainProject/Controllers/ShoppingCartController.cs
using TPP_MainProject.Models;
using TPP_MainProject.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TPP_MainProject.Models.entities;
using TPP_MainProject.Models.repository;

namespace TPP_MainProject.Controllers
{
    public class ShoppingCartController : Controller
    {
        UnitOfWork unityOfWork = new UnitOfWork();
        //ApplicationDbContext storeDB = new ApplicationDbContext();
        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Set up our ViewModel
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };
            // Return the view
            return View(viewModel);
        }
        //
        // GET: /Store/AddToCart/5
        [HttpPost]
        public ActionResult AddToCart(int id)
        {
            // Retrieve the item from the database
            var addedItem = unityOfWork.ProductItemRepository.dbSet
                .Single(item => item.ID == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            int count = cart.AddToCart(addedItem);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = Server.HtmlEncode(addedItem.Name) +
                    " has been added to your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = count,
                DeleteId = id
            };
            return Json(results);

            // Go back to the main store page for more shopping
            // return RedirectToAction("Index");
        }
        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public ActionResult RemoveFromCart(int id)
        {
            // Remove the item from the cart
            var cart = ShoppingCart.GetCart(this.HttpContext);

            // Get the name of the item to display confirmation

            // Get the name of the album to display confirmation
            string itemName = unityOfWork.ProductItemRepository.dbSet
                .Single(item => item.ID == id).Name;

            // Remove from cart
            int itemCount = cart.RemoveFromCart(id);

            // Display the confirmation message
            var results = new ShoppingCartRemoveViewModel
            {
                Message = "One (1) " + Server.HtmlEncode(itemName) +
                    " has been removed from your shopping cart.",
                CartTotal = cart.GetTotal(),
                CartCount = cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
            return Json(results);
        }
        //
        // GET: /ShoppingCart/CartSummary
        [ChildActionOnly]
        public ActionResult CartSummary()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);

            ViewData["CartCount"] = cart.GetCount();
            return PartialView("CartSummary");
        }
    }
}

TPP_MainProject/Views/ShoppingCart/CartSummary.cshtml
<a href='@Url.Action("Index", "ShoppingCart")'><strong>Cart</strong>  <span id="cart-status" class="badge">@ViewData["CartCount"]</span></a>

TPP_MainProject/Views/ShoppingCart/Index.cshtml
@model TPP_MainProject.Models.ViewModels.ShoppingCartViewModel

@{
    ViewBag.Title = "Shopping Cart";
}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text(data.CartCount);
                    });
            }
        });
    });
</script>
<h3 style="color:#007194; font-weight:bold">
    <em>Review</em> your cart:
</h3>

@{

    if (Model.CartItems.Count > 0)
    {
        <div class="panel panel-info" style=" background:#ffffcc">
            <div class="panel-heading" style=" background:#ffffcc">
                <h3 class="panel-title" style=" background:#ffffcc; color:#0B610B; font-weight:bold">Order Summary</h3>
            </div>
            <div class="panel-body" style=" background:#ffffcc">

                <div id="update-message">
                </div>
                <table class="table table-striped table-hover" style=" background:#ffffcc">
                    <thead>
                        <tr>
                            <th>
                                Item Name
                            </th>
                            <th>
                                Price (each)
                            </th>
                            <th>
                                Quantity
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    @foreach (var item in Model.CartItems)
                    {
                        <tr id="row-@item.ProductItemId" style=" background:#ffffcc">
                            <td style=" background:#ffffcc">
                                @Html.ActionLink(item.ProductItem.Name, "Details", "Items", new { id = item.ProductItemId }, null)
                            </td>
                            <td style=" background:#ffffcc">
                                @item.ProductItem.Price
                            </td>
                            <td id="item-count-@item.ProductItemId" style=" background:#ffffcc">
                                @item.Count
                            </td>
                            <td style=" background:#ffffcc">
                                <a href="#" class="RemoveLink" style=" background:#ffffcc"
                                   data-id="@item.ProductItemId">
                                    Remove
                                    from cart
                                </a>
                            </td>
                        </tr>
                    }
                    <tr class="info" style=" background:#ffffcc">
                        <td style=" background:#ffffcc; color:#0B610B; font-weight:bold">
                            Total
                        </td>
                        <td style=" background:#ffffcc"></td>
                        <td style=" background:#ffffcc"></td>
                        <td id="cart-total" style=" background:#ffffcc">
                            @Model.CartTotal
                        </td>
                    </tr>
                </table>
                <button type="button" class="btn btn-success btn-sm" onclick="location.href='@Url.Action("AddressAndPayment", "Checkout")'">
                    Check Out &raquo;
                </button>
            </div>
        </div>
    }
    else
    {
        <div>
            <p>
                There are no items in your cart currently. Please shop for something and add items..
            </p>
        </div>
    }
}